# Generated by Django 2.0.3 on 2018-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codebar', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nutri_code', models.CharField(max_length=1)),
                ('link', models.CharField(max_length=255)),
                ('picture', models.URLField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugars', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
