# Generated by Django 2.0.3 on 2018-04-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180409_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
