# Generated by Django 2.0.3 on 2018-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180409_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
